services:
  - type: web
    name: proposal-checker
    runtime: node
    plan: free
    buildCommand: npm install --prefix frontend && npm install --prefix backend && npm run build --prefix frontend
    startCommand: npm run start --prefix backend
    envVars:
      - key: DOCUMENT_STORAGE
        value: database
      - key: JWT_SECRET
        generateValue: true
